apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f netpicker.yml
    kompose.version: 1.34.0 (HEAD)
    service.netpicker.io: agent
  labels:
    io.kompose.service: agent
  name: agent
spec:
  ports:
    - name: "5514"
      port: 5514
      protocol: UDP
      targetPort: 5514
    - name: "6601"
      port: 6601
      targetPort: 6601
    - name: "6514"
      port: 6514
      targetPort: 6514
    - name: "8765"
      port: 8765
      targetPort: 8765
    - name: "9876"
      port: 9876
      targetPort: 9876
  selector:
    io.kompose.service: agent
