apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f netpicker.yml
    kompose.version: 1.34.0 (HEAD)
    service.netpicker.io: agent
  labels:
    io.kompose.service: agent
  name: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: agent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f netpicker.yml
        kompose.version: 1.34.0 (HEAD)
        service.netpicker.io: agent
      labels:
        io.kompose.service: agent
    spec:
      containers:
        - env:
            - name: CLI_PROXY_ADDR
              value: 0.0.0.0
            - name: SHENV_PRIVILEGED_PLATFORMS
              value: privileged_platform
            - name: SHENV_SHOW_RUN_nokia_srl
              value: info
          image: netpicker/agent:latest
          livenessProbe:
            exec:
              command:
                - echo LST | nc -v localhost 8765
            initialDelaySeconds: 2
            periodSeconds: 5
          name: agent
          ports:
            - containerPort: 5514
              protocol: UDP
            - containerPort: 6601
              protocol: TCP
            - containerPort: 6514
              protocol: TCP
            - containerPort: 8765
              protocol: TCP
            - containerPort: 9876
              protocol: TCP
          volumeMounts:
            - mountPath: /agent-config
              name: config
            - mountPath: /run/secrets
              name: secret
            - mountPath: /transferium
              name: transferium
      hostname: agent
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: secret
          persistentVolumeClaim:
            claimName: secret
        - name: transferium
          persistentVolumeClaim:
            claimName: transferium
