apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f netpicker.yml
    kompose.version: 1.34.0 (HEAD)
    service.netpicker.io: api
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: api
