apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f netpicker.yml
    kompose.version: 1.34.0 (HEAD)
    service.netpicker.io: api
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f netpicker.yml
        kompose.version: 1.34.0 (HEAD)
        service.netpicker.io: api
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: ALLOWED_ORIGINS
              value: '["*"]'
            - name: AUTH0_AUDIENCE
              value: n/a
            - name: AUTH0_CLIENT_ID
              value: n/a
            - name: AUTH0_CLIENT_SECRET
              value: n/a
            - name: AUTH0_TENANT
              value: n/a
            - name: AUTH_BACKEND
              value: netyce_alchemy
            - name: BEAT_DB_URI
              value: postgresql+psycopg2://netpicker:netpicker@db/netpicker
            - name: CELERY_BROKER_URL
              value: redis://redis
            - name: CELERY_RESULT_BACKEND
              value: redis://redis
            - name: CLI_PROXY_HOST
              value: agent
            - name: DB_URI
              value: postgresql+asyncpg://netpicker:netpicker@db/netpicker
            - name: GIT_REPO_MANAGER
              value: '["gitd",9419]'
            - name: GIT_SERVER
              value: git://gitd
            - name: INIT_PASSWORD
              value: "12345678"
            - name: INIT_TENANT
              value: default
            - name: INIT_USER
              value: admin@admin.com
            - name: JWT_ALGORITHM
              value: HS256
            - name: JWT_AUDIENCE
              value: netpicker
            - name: JWT_SECRET
              value: ew9023cnkljfcnsdlkfsfdhs
            - name: NETBOX_API
              value: https://netbox-endpoint/
            - name: NETBOX_TOKEN
              value: netbox_token_here
            - name: PERSISTENT_VOLUME_PATH
              value: /data/policy-repository
            - name: REDIS_URL
              value: redis://redis
            - name: SLURPIT_APIKEY
              value: slurpit_apikey_here
            - name: SLURPIT_URL
              value: https://slurpit-endpoint/
            - name: UVICORN_ROOT_PATH
              value: /
            - name: WORKDIR_VOLUME_PATH
              value: /data/policy-workdir
          image: netpicker/api
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8000/api/v1/status
            initialDelaySeconds: 15
            periodSeconds: 5
          name: api
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: policy-data
      restartPolicy: Always
      volumes:
        - name: policy-data
          persistentVolumeClaim:
            claimName: policy-data
