apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f netpicker.yml
    kompose.version: 1.34.0 (HEAD)
    service.netpicker.io: front-end
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: frontend
