apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f netpicker.yml
    kompose.version: 1.34.0 (HEAD)
    service.netpicker.io: front-end
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f netpicker.yml
        kompose.version: 1.34.0 (HEAD)
        service.netpicker.io: front-end
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: netpicker/frontend
          name: frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
