apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f netpicker.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: gitd
  name: gitd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gitd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f netpicker.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: gitd
    spec:
      containers:
        - image: netpicker/gitd
          livenessProbe:
            exec:
              command:
                - echo "PING" | nc -v localhost 9419
            initialDelaySeconds: 15
            periodSeconds: 5
          name: gitd
          ports:
            - containerPort: 9418
              protocol: TCP
            - containerPort: 9419
              protocol: TCP
          volumeMounts:
            - mountPath: /git
              name: git
      restartPolicy: Always
      volumes:
        - name: git
          persistentVolumeClaim:
            claimName: git
