apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f netpicker.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: gitd
  name: gitd
spec:
  ports:
    - name: "9418"
      port: 9418
      targetPort: 9418
    - name: "9419"
      port: 9419
      targetPort: 9419
  selector:
    io.kompose.service: gitd
