apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f netpicker.yml
    kompose.version: 1.34.0 (HEAD)
    service.netpicker.io: kibbitzer
  labels:
    io.kompose.service: kibbitzer
  name: kibbitzer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibbitzer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f netpicker.yml
        kompose.version: 1.34.0 (HEAD)
        service.netpicker.io: kibbitzer
      labels:
        io.kompose.service: kibbitzer
    spec:
      containers:
        - env:
            - name: LOG_LEVEL
              value: DEBUG
            - name: SHENV_API_URL
              value: http://api:8000
          image: netpicker/kibbitzer
          livenessProbe:
            exec:
              command:
                - echo "PING Mac" | nc -v 127.0.0.1 9696
            initialDelaySeconds: 15
            periodSeconds: 30
          name: kibbitzer
          volumeMounts:
            - mountPath: /run/secrets
              name: secret
      restartPolicy: Always
      volumes:
        - name: secret
          persistentVolumeClaim:
            claimName: secret
