apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f netpicker.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: swagger
  name: swagger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: swagger
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f netpicker.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: swagger
    spec:
      containers:
        - env:
            - name: SWAGGER_JSON_URL
              value: /openapi.json
            - name: TRY_IT_OUT_ENABLED
              value: "true"
          image: swaggerapi/swagger-ui
          name: swagger
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
