apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: transferium
  name: transferium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
